# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atolyeEkleSil.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atolyeEkleSil(object):
    def setupUi(self, atolyeEkleSil):
        atolyeEkleSil.setObjectName("atolyeEkleSil")
        atolyeEkleSil.resize(631, 384)
        self.atolyeAdi = QtWidgets.QTextEdit(atolyeEkleSil)
        self.atolyeAdi.setGeometry(QtCore.QRect(90, 50, 221, 30))
        self.atolyeAdi.setObjectName("atolyeAdi")
        self.kaydetButonu = QtWidgets.QPushButton(atolyeEkleSil)
        self.kaydetButonu.setGeometry(QtCore.QRect(90, 90, 220, 30))
        self.kaydetButonu.setObjectName("kaydetButonu")
        self.label = QtWidgets.QLabel(atolyeEkleSil)
        self.label.setGeometry(QtCore.QRect(12, 50, 71, 30))
        self.label.setObjectName("label")
        self.silButonu = QtWidgets.QPushButton(atolyeEkleSil)
        self.silButonu.setGeometry(QtCore.QRect(340, 300, 256, 30))
        self.silButonu.setObjectName("silButonu")
        self.atolyeListesi = QtWidgets.QTableView(atolyeEkleSil)
        self.atolyeListesi.setGeometry(QtCore.QRect(340, 90, 256, 192))
        self.atolyeListesi.setAutoFillBackground(False)
        self.atolyeListesi.setAlternatingRowColors(True)
        self.atolyeListesi.setIconSize(QtCore.QSize(0, 0))
        self.atolyeListesi.setSortingEnabled(True)
        self.atolyeListesi.setObjectName("atolyeListesi")
        self.arama = QtWidgets.QLineEdit(atolyeEkleSil)
        self.arama.setGeometry(QtCore.QRect(340, 50, 256, 30))
        self.arama.setObjectName("arama")

        self.retranslateUi(atolyeEkleSil)
        QtCore.QMetaObject.connectSlotsByName(atolyeEkleSil)

    def retranslateUi(self, atolyeEkleSil):
        _translate = QtCore.QCoreApplication.translate
        atolyeEkleSil.setWindowTitle(_translate("atolyeEkleSil", "Atölye Ekle/Sil"))
        self.atolyeAdi.setHtml(_translate("atolyeEkleSil", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.kaydetButonu.setText(_translate("atolyeEkleSil", "Ekle"))
        self.label.setText(_translate("atolyeEkleSil", "Atölye adı:"))
        self.silButonu.setText(_translate("atolyeEkleSil", "Sil"))
