# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musteriEkleSil.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_MusteriEkleSil(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(631, 384)
        self.musteriAdi = QtWidgets.QTextEdit(Form)
        self.musteriAdi.setGeometry(QtCore.QRect(90, 50, 221, 30))
        self.musteriAdi.setObjectName("musteriAdi")
        self.kaydetButonu = QtWidgets.QPushButton(Form)
        self.kaydetButonu.setGeometry(QtCore.QRect(90, 90, 220, 30))
        self.kaydetButonu.setObjectName("kaydetButonu")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(12, 50, 71, 30))
        self.label.setObjectName("label")
        self.silButonu = QtWidgets.QPushButton(Form)
        self.silButonu.setGeometry(QtCore.QRect(340, 300, 256, 30))
        self.silButonu.setObjectName("silButonu")
        self.musteriListesi = QtWidgets.QTableView(Form)
        self.musteriListesi.setGeometry(QtCore.QRect(340, 90, 256, 192))
        self.musteriListesi.setAutoFillBackground(False)
        self.musteriListesi.setAlternatingRowColors(True)
        self.musteriListesi.setIconSize(QtCore.QSize(0, 0))
        self.musteriListesi.setSortingEnabled(True)
        self.musteriListesi.setObjectName("musteriListesi")
        self.arama = QtWidgets.QLineEdit(Form)
        self.arama.setGeometry(QtCore.QRect(340, 50, 256, 30))
        self.arama.setObjectName("arama")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Müşteri Ekle/Sil"))
        self.musteriAdi.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.kaydetButonu.setText(_translate("Form", "Ekle"))
        self.label.setText(_translate("Form", "Müşteri adı:"))
        self.silButonu.setText(_translate("Form", "Sil"))
